sudo: false
language: cpp
compiler: clang

apt:
  sources:
    - boost-latest
    - ubuntu-toolchain-r-test
  packages:
    - valgrind
    - libboost1.55-all-dev
    - g++-5

matrix:
  include:

    - env: COMPILER=clang-3.6
      addons: &clang36
        apt:
          sources:
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6

    - env: COMPILER=g++-5

install:
  - CXX="$COMPILER"

script:
  - cmake .
  - make VERBOSE=1
  - ./unittest
