sudo: false
language: cpp
compiler:
  - clang
  - g++

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - boost-latest
    packages:
        - g++-4.9
        - libboost1.55-all-dev
        - coreutils

# Configure g++ version
install:
  - if [ "$CXX" == "g++" ]; then CXX=/usr/bin/g++-4.9; fi

# command to run tests
script:
  - cmake .
  - make
  - ./unittest
