sudo: false
cache: apt
language: cpp

matrix:
  include:

    - env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libboost1.55-all-dev
            - g++-5
            - libkyotocabinet-dev

# can't link on travis :(
#    - env: COMPILER=g++-5
#      addons:
#        apt:
#          sources:
#            - boost-latest
#            - ubuntu-toolchain-r-test
#          packages:
#            - libboost1.55-all-dev
#            - g++-5

install:
  - CXX="$COMPILER"

script:
  - cmake .
  - make -j VERBOSE=1
  - ./unittest

