sudo: false
language: cpp
compiler:
  - clang

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - boost-latest
    packages:
        #- gcc-4.9
        #- g++-4.9
        - libboost1.55-all-dev

# Configure g++ version
#install:
#  - if [ "$CXX" == "g++" ]; then CXX=/usr/bin/g++-4.9; fi

# command to run tests
script:
  - cmake .
  - make VERBOSE=1
  - ./unittest
