# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rustyrick/git/TorrentSync

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rustyrick/git/TorrentSync

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rustyrick/git/TorrentSync/CMakeFiles /home/rustyrick/git/TorrentSync/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rustyrick/git/TorrentSync/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TorrentSync

# Build rule for target.
TorrentSync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TorrentSync
.PHONY : TorrentSync

# fast build rule for target.
TorrentSync/fast:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/build
.PHONY : TorrentSync/fast

#=============================================================================
# Target rules for targets named unittest

# Build rule for target.
unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest
.PHONY : unittest

# fast build rule for target.
unittest/fast:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/build
.PHONY : unittest/fast

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/torrentsync/dht/Address.o: test/torrentsync/dht/Address.cpp.o
.PHONY : test/torrentsync/dht/Address.o

# target to build an object file
test/torrentsync/dht/Address.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/Address.cpp.o
.PHONY : test/torrentsync/dht/Address.cpp.o

test/torrentsync/dht/Address.i: test/torrentsync/dht/Address.cpp.i
.PHONY : test/torrentsync/dht/Address.i

# target to preprocess a source file
test/torrentsync/dht/Address.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/Address.cpp.i
.PHONY : test/torrentsync/dht/Address.cpp.i

test/torrentsync/dht/Address.s: test/torrentsync/dht/Address.cpp.s
.PHONY : test/torrentsync/dht/Address.s

# target to generate assembly for a file
test/torrentsync/dht/Address.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/Address.cpp.s
.PHONY : test/torrentsync/dht/Address.cpp.s

test/torrentsync/dht/AddressBucket.o: test/torrentsync/dht/AddressBucket.cpp.o
.PHONY : test/torrentsync/dht/AddressBucket.o

# target to build an object file
test/torrentsync/dht/AddressBucket.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressBucket.cpp.o
.PHONY : test/torrentsync/dht/AddressBucket.cpp.o

test/torrentsync/dht/AddressBucket.i: test/torrentsync/dht/AddressBucket.cpp.i
.PHONY : test/torrentsync/dht/AddressBucket.i

# target to preprocess a source file
test/torrentsync/dht/AddressBucket.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressBucket.cpp.i
.PHONY : test/torrentsync/dht/AddressBucket.cpp.i

test/torrentsync/dht/AddressBucket.s: test/torrentsync/dht/AddressBucket.cpp.s
.PHONY : test/torrentsync/dht/AddressBucket.s

# target to generate assembly for a file
test/torrentsync/dht/AddressBucket.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressBucket.cpp.s
.PHONY : test/torrentsync/dht/AddressBucket.cpp.s

test/torrentsync/dht/AddressData.o: test/torrentsync/dht/AddressData.cpp.o
.PHONY : test/torrentsync/dht/AddressData.o

# target to build an object file
test/torrentsync/dht/AddressData.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressData.cpp.o
.PHONY : test/torrentsync/dht/AddressData.cpp.o

test/torrentsync/dht/AddressData.i: test/torrentsync/dht/AddressData.cpp.i
.PHONY : test/torrentsync/dht/AddressData.i

# target to preprocess a source file
test/torrentsync/dht/AddressData.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressData.cpp.i
.PHONY : test/torrentsync/dht/AddressData.cpp.i

test/torrentsync/dht/AddressData.s: test/torrentsync/dht/AddressData.cpp.s
.PHONY : test/torrentsync/dht/AddressData.s

# target to generate assembly for a file
test/torrentsync/dht/AddressData.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressData.cpp.s
.PHONY : test/torrentsync/dht/AddressData.cpp.s

test/torrentsync/dht/AddressTree.o: test/torrentsync/dht/AddressTree.cpp.o
.PHONY : test/torrentsync/dht/AddressTree.o

# target to build an object file
test/torrentsync/dht/AddressTree.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressTree.cpp.o
.PHONY : test/torrentsync/dht/AddressTree.cpp.o

test/torrentsync/dht/AddressTree.i: test/torrentsync/dht/AddressTree.cpp.i
.PHONY : test/torrentsync/dht/AddressTree.i

# target to preprocess a source file
test/torrentsync/dht/AddressTree.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressTree.cpp.i
.PHONY : test/torrentsync/dht/AddressTree.cpp.i

test/torrentsync/dht/AddressTree.s: test/torrentsync/dht/AddressTree.cpp.s
.PHONY : test/torrentsync/dht/AddressTree.s

# target to generate assembly for a file
test/torrentsync/dht/AddressTree.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/AddressTree.cpp.s
.PHONY : test/torrentsync/dht/AddressTree.cpp.s

test/torrentsync/dht/Node.o: test/torrentsync/dht/Node.cpp.o
.PHONY : test/torrentsync/dht/Node.o

# target to build an object file
test/torrentsync/dht/Node.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/Node.cpp.o
.PHONY : test/torrentsync/dht/Node.cpp.o

test/torrentsync/dht/Node.i: test/torrentsync/dht/Node.cpp.i
.PHONY : test/torrentsync/dht/Node.i

# target to preprocess a source file
test/torrentsync/dht/Node.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/Node.cpp.i
.PHONY : test/torrentsync/dht/Node.cpp.i

test/torrentsync/dht/Node.s: test/torrentsync/dht/Node.cpp.s
.PHONY : test/torrentsync/dht/Node.s

# target to generate assembly for a file
test/torrentsync/dht/Node.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/Node.cpp.s
.PHONY : test/torrentsync/dht/Node.cpp.s

test/torrentsync/dht/RoutingTable.o: test/torrentsync/dht/RoutingTable.cpp.o
.PHONY : test/torrentsync/dht/RoutingTable.o

# target to build an object file
test/torrentsync/dht/RoutingTable.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/RoutingTable.cpp.o
.PHONY : test/torrentsync/dht/RoutingTable.cpp.o

test/torrentsync/dht/RoutingTable.i: test/torrentsync/dht/RoutingTable.cpp.i
.PHONY : test/torrentsync/dht/RoutingTable.i

# target to preprocess a source file
test/torrentsync/dht/RoutingTable.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/RoutingTable.cpp.i
.PHONY : test/torrentsync/dht/RoutingTable.cpp.i

test/torrentsync/dht/RoutingTable.s: test/torrentsync/dht/RoutingTable.cpp.s
.PHONY : test/torrentsync/dht/RoutingTable.s

# target to generate assembly for a file
test/torrentsync/dht/RoutingTable.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/test/torrentsync/dht/RoutingTable.cpp.s
.PHONY : test/torrentsync/dht/RoutingTable.cpp.s

torrentsync/dht/Address.o: torrentsync/dht/Address.cpp.o
.PHONY : torrentsync/dht/Address.o

# target to build an object file
torrentsync/dht/Address.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/Address.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/Address.cpp.o
.PHONY : torrentsync/dht/Address.cpp.o

torrentsync/dht/Address.i: torrentsync/dht/Address.cpp.i
.PHONY : torrentsync/dht/Address.i

# target to preprocess a source file
torrentsync/dht/Address.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/Address.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/Address.cpp.i
.PHONY : torrentsync/dht/Address.cpp.i

torrentsync/dht/Address.s: torrentsync/dht/Address.cpp.s
.PHONY : torrentsync/dht/Address.s

# target to generate assembly for a file
torrentsync/dht/Address.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/Address.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/Address.cpp.s
.PHONY : torrentsync/dht/Address.cpp.s

torrentsync/dht/AddressData.o: torrentsync/dht/AddressData.cpp.o
.PHONY : torrentsync/dht/AddressData.o

# target to build an object file
torrentsync/dht/AddressData.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/AddressData.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/AddressData.cpp.o
.PHONY : torrentsync/dht/AddressData.cpp.o

torrentsync/dht/AddressData.i: torrentsync/dht/AddressData.cpp.i
.PHONY : torrentsync/dht/AddressData.i

# target to preprocess a source file
torrentsync/dht/AddressData.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/AddressData.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/AddressData.cpp.i
.PHONY : torrentsync/dht/AddressData.cpp.i

torrentsync/dht/AddressData.s: torrentsync/dht/AddressData.cpp.s
.PHONY : torrentsync/dht/AddressData.s

# target to generate assembly for a file
torrentsync/dht/AddressData.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/AddressData.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/AddressData.cpp.s
.PHONY : torrentsync/dht/AddressData.cpp.s

torrentsync/dht/AddressTree.o: torrentsync/dht/AddressTree.cpp.o
.PHONY : torrentsync/dht/AddressTree.o

# target to build an object file
torrentsync/dht/AddressTree.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/AddressTree.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/AddressTree.cpp.o
.PHONY : torrentsync/dht/AddressTree.cpp.o

torrentsync/dht/AddressTree.i: torrentsync/dht/AddressTree.cpp.i
.PHONY : torrentsync/dht/AddressTree.i

# target to preprocess a source file
torrentsync/dht/AddressTree.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/AddressTree.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/AddressTree.cpp.i
.PHONY : torrentsync/dht/AddressTree.cpp.i

torrentsync/dht/AddressTree.s: torrentsync/dht/AddressTree.cpp.s
.PHONY : torrentsync/dht/AddressTree.s

# target to generate assembly for a file
torrentsync/dht/AddressTree.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/AddressTree.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/AddressTree.cpp.s
.PHONY : torrentsync/dht/AddressTree.cpp.s

torrentsync/dht/Node.o: torrentsync/dht/Node.cpp.o
.PHONY : torrentsync/dht/Node.o

# target to build an object file
torrentsync/dht/Node.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/Node.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/Node.cpp.o
.PHONY : torrentsync/dht/Node.cpp.o

torrentsync/dht/Node.i: torrentsync/dht/Node.cpp.i
.PHONY : torrentsync/dht/Node.i

# target to preprocess a source file
torrentsync/dht/Node.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/Node.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/Node.cpp.i
.PHONY : torrentsync/dht/Node.cpp.i

torrentsync/dht/Node.s: torrentsync/dht/Node.cpp.s
.PHONY : torrentsync/dht/Node.s

# target to generate assembly for a file
torrentsync/dht/Node.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/Node.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/Node.cpp.s
.PHONY : torrentsync/dht/Node.cpp.s

torrentsync/dht/RoutingTable.o: torrentsync/dht/RoutingTable.cpp.o
.PHONY : torrentsync/dht/RoutingTable.o

# target to build an object file
torrentsync/dht/RoutingTable.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/RoutingTable.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/RoutingTable.cpp.o
.PHONY : torrentsync/dht/RoutingTable.cpp.o

torrentsync/dht/RoutingTable.i: torrentsync/dht/RoutingTable.cpp.i
.PHONY : torrentsync/dht/RoutingTable.i

# target to preprocess a source file
torrentsync/dht/RoutingTable.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/RoutingTable.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/RoutingTable.cpp.i
.PHONY : torrentsync/dht/RoutingTable.cpp.i

torrentsync/dht/RoutingTable.s: torrentsync/dht/RoutingTable.cpp.s
.PHONY : torrentsync/dht/RoutingTable.s

# target to generate assembly for a file
torrentsync/dht/RoutingTable.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/RoutingTable.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/RoutingTable.cpp.s
.PHONY : torrentsync/dht/RoutingTable.cpp.s

torrentsync/dht/message/BencodedMessage.o: torrentsync/dht/message/BencodedMessage.cpp.o
.PHONY : torrentsync/dht/message/BencodedMessage.o

# target to build an object file
torrentsync/dht/message/BencodedMessage.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/BencodedMessage.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/BencodedMessage.cpp.o
.PHONY : torrentsync/dht/message/BencodedMessage.cpp.o

torrentsync/dht/message/BencodedMessage.i: torrentsync/dht/message/BencodedMessage.cpp.i
.PHONY : torrentsync/dht/message/BencodedMessage.i

# target to preprocess a source file
torrentsync/dht/message/BencodedMessage.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/BencodedMessage.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/BencodedMessage.cpp.i
.PHONY : torrentsync/dht/message/BencodedMessage.cpp.i

torrentsync/dht/message/BencodedMessage.s: torrentsync/dht/message/BencodedMessage.cpp.s
.PHONY : torrentsync/dht/message/BencodedMessage.s

# target to generate assembly for a file
torrentsync/dht/message/BencodedMessage.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/BencodedMessage.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/BencodedMessage.cpp.s
.PHONY : torrentsync/dht/message/BencodedMessage.cpp.s

torrentsync/dht/message/Message.o: torrentsync/dht/message/Message.cpp.o
.PHONY : torrentsync/dht/message/Message.o

# target to build an object file
torrentsync/dht/message/Message.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/Message.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/Message.cpp.o
.PHONY : torrentsync/dht/message/Message.cpp.o

torrentsync/dht/message/Message.i: torrentsync/dht/message/Message.cpp.i
.PHONY : torrentsync/dht/message/Message.i

# target to preprocess a source file
torrentsync/dht/message/Message.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/Message.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/Message.cpp.i
.PHONY : torrentsync/dht/message/Message.cpp.i

torrentsync/dht/message/Message.s: torrentsync/dht/message/Message.cpp.s
.PHONY : torrentsync/dht/message/Message.s

# target to generate assembly for a file
torrentsync/dht/message/Message.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/Message.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/Message.cpp.s
.PHONY : torrentsync/dht/message/Message.cpp.s

torrentsync/dht/message/Ping.o: torrentsync/dht/message/Ping.cpp.o
.PHONY : torrentsync/dht/message/Ping.o

# target to build an object file
torrentsync/dht/message/Ping.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/Ping.cpp.o
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/Ping.cpp.o
.PHONY : torrentsync/dht/message/Ping.cpp.o

torrentsync/dht/message/Ping.i: torrentsync/dht/message/Ping.cpp.i
.PHONY : torrentsync/dht/message/Ping.i

# target to preprocess a source file
torrentsync/dht/message/Ping.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/Ping.cpp.i
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/Ping.cpp.i
.PHONY : torrentsync/dht/message/Ping.cpp.i

torrentsync/dht/message/Ping.s: torrentsync/dht/message/Ping.cpp.s
.PHONY : torrentsync/dht/message/Ping.s

# target to generate assembly for a file
torrentsync/dht/message/Ping.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/dht/message/Ping.cpp.s
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/torrentsync/dht/message/Ping.cpp.s
.PHONY : torrentsync/dht/message/Ping.cpp.s

torrentsync/main.o: torrentsync/main.cpp.o
.PHONY : torrentsync/main.o

# target to build an object file
torrentsync/main.cpp.o:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/main.cpp.o
.PHONY : torrentsync/main.cpp.o

torrentsync/main.i: torrentsync/main.cpp.i
.PHONY : torrentsync/main.i

# target to preprocess a source file
torrentsync/main.cpp.i:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/main.cpp.i
.PHONY : torrentsync/main.cpp.i

torrentsync/main.s: torrentsync/main.cpp.s
.PHONY : torrentsync/main.s

# target to generate assembly for a file
torrentsync/main.cpp.s:
	$(MAKE) -f CMakeFiles/TorrentSync.dir/build.make CMakeFiles/TorrentSync.dir/torrentsync/main.cpp.s
.PHONY : torrentsync/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... TorrentSync"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... unittest"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/torrentsync/dht/Address.o"
	@echo "... test/torrentsync/dht/Address.i"
	@echo "... test/torrentsync/dht/Address.s"
	@echo "... test/torrentsync/dht/AddressBucket.o"
	@echo "... test/torrentsync/dht/AddressBucket.i"
	@echo "... test/torrentsync/dht/AddressBucket.s"
	@echo "... test/torrentsync/dht/AddressData.o"
	@echo "... test/torrentsync/dht/AddressData.i"
	@echo "... test/torrentsync/dht/AddressData.s"
	@echo "... test/torrentsync/dht/AddressTree.o"
	@echo "... test/torrentsync/dht/AddressTree.i"
	@echo "... test/torrentsync/dht/AddressTree.s"
	@echo "... test/torrentsync/dht/Node.o"
	@echo "... test/torrentsync/dht/Node.i"
	@echo "... test/torrentsync/dht/Node.s"
	@echo "... test/torrentsync/dht/RoutingTable.o"
	@echo "... test/torrentsync/dht/RoutingTable.i"
	@echo "... test/torrentsync/dht/RoutingTable.s"
	@echo "... torrentsync/dht/Address.o"
	@echo "... torrentsync/dht/Address.i"
	@echo "... torrentsync/dht/Address.s"
	@echo "... torrentsync/dht/AddressData.o"
	@echo "... torrentsync/dht/AddressData.i"
	@echo "... torrentsync/dht/AddressData.s"
	@echo "... torrentsync/dht/AddressTree.o"
	@echo "... torrentsync/dht/AddressTree.i"
	@echo "... torrentsync/dht/AddressTree.s"
	@echo "... torrentsync/dht/Node.o"
	@echo "... torrentsync/dht/Node.i"
	@echo "... torrentsync/dht/Node.s"
	@echo "... torrentsync/dht/RoutingTable.o"
	@echo "... torrentsync/dht/RoutingTable.i"
	@echo "... torrentsync/dht/RoutingTable.s"
	@echo "... torrentsync/dht/message/BencodedMessage.o"
	@echo "... torrentsync/dht/message/BencodedMessage.i"
	@echo "... torrentsync/dht/message/BencodedMessage.s"
	@echo "... torrentsync/dht/message/Message.o"
	@echo "... torrentsync/dht/message/Message.i"
	@echo "... torrentsync/dht/message/Message.s"
	@echo "... torrentsync/dht/message/Ping.o"
	@echo "... torrentsync/dht/message/Ping.i"
	@echo "... torrentsync/dht/message/Ping.s"
	@echo "... torrentsync/main.o"
	@echo "... torrentsync/main.i"
	@echo "... torrentsync/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

